#!/bin/bash
echo -e "$1" | grep -n . | grep ^$2: | cut -d: -f1- | tr \ , \\n | grep -n .
echo -n "enter word num "
read wd
echo -e "$1" | grep -n . | grep ^$2: | cut -d: -f1- | tr \ , \\n | grep -n . | grep ^$wd: | cut -d: -f1-
